environment: playground

global:
  security:
    allowInsecureImages: false

image:
  name: ghcr.io/ifrcgo/go-api
  tag: develop.02d8c49

ingress:
  enabled: true
  host: goadmin-playground.ifrc.org
  className: nginx
  tls:
    enabled: true
    secretName: ifrcgo-api-helm-secret-cert

serviceAccount:
  create: true
  name: service-token-reader
  automount: true
  labels:
    azure.workload.identity/use: "true"

api:
  domain: go-playground.ifrc.org
  tls:
    enabled: false

# PostgreSQL (disabled — using Azure PostgreSQL)
postgresql:
  enabled: false

redis:
  image:
    repository: bitnamilegacy/redis
  master:
    persistence:
      size: .1Gi
      storageClass: longhorn
  resources:
    requests:
      cpu: "0.1"
      memory: .1Gi
    limits:
      cpu: "4"
      memory: .5Gi

# Azure Key Vault — values come from terraform output
# azure:
#   aksSecretsProviderAvailable: true
# TODO(susilnem): fill this from terraform output
# keyvault:
#   name: ""
#   clientId: ""
#   tenantId: "a2b53be5-734e-4e6c-ab0d-d184f60fd917"

sshBastion:
  enabled: false

env:
  GO_ENVIRONMENT: playground
  DOMAIN_NAME: goadmin-playground.ifrc.org
  FRONTEND_URL: https://go-playground.ifrc.org
  API_FQDN: go-playground.ifrc.org
  AUTO_TRANSLATION_TRANSLATOR: 'lang.translation.DummyTranslator'
  # Set this from Env or update it from terrafrom output manaually?
  DJANGO_DB_NAME: "go-apiplaygrounddb"
