#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: alert-hub
#  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#  annotations:
#    # Image list for ArgoCD Image Updater to track
#    argocd-image-updater.argoproj.io/image-list: |
#      api=docker pull ghcr.io/ifrcgo/alert-hub-backend:develop.448e946
#
#    # Set the update strategy to pick the latest matching tag
#    argocd-image-updater.argoproj.io/api.update-strategy: digest
#
#    # Specifying Helm parameter names
#    argocd-image-updater.argoproj.io/api.helm.image-name: image.repository
#    argocd-image-updater.argoproj.io/api.helm.image-tag: image.tag
#spec:
#  project: default
#  source:
#    repoURL: https://github.com/IFRCGo/alert-hub-backend
#    targetRevision: feature/helm-chart-secrets-config
#    path: helm
#    helm:
#      valueFiles:
#        - values-sandbox.yaml
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: alert-hub
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - CreateNamespace=true

#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: alert-hub
#  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#  annotations:
#    # Image list for ArgoCD Image Updater to track
#    argocd-image-updater.argoproj.io/image-list: |
#      api=ghcr.io/ifrcgo/alert-hub-backend
#
#    # Set the update strategy to pick the latest matching tag
#    argocd-image-updater.argoproj.io/api.update-strategy: newest-build
#    argocd-image-updater.argoproj.io/api.allow-tags: regexp:^develop.*$
#
#    argocd-image-updater.argoproj.io/api.helm.image-name: image.name
#    argocd-image-updater.argoproj.io/api.helm.image-tag: image.tag
#
#    argocd-image-updater.argoproj.io/api.pull-secret: pullsecret:argocd/ghcr-secret
#spec:
#  project: default
#  source:
#    repoURL: ghcr.io/ifrcgo/alert-hub-backend
#    chart: ifrcgo-alert-hub-helm
#    targetRevision: 0.0.1-develop.d8e2386
#    helm:
##      parameters:
##        - name: image.tag
##          value: "develop.d8e2386"
#      valuesObject:
#
#      valueFiles:
#        - values-sandbox.yaml
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: alert-hub
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - CreateNamespace=true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-hub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/IFRCGo/alert-hub-backend
    targetRevision: fix/azure-identity-issue
    path: helm
#    repoURL: ghcr.io/ifrcgo/alert-hub-backend
#    chart: ifrcgo-alert-hub-helm
#    targetRevision: 0.0.1-develop.4bceb7d
    helm:
      valuesObject:
        ingress:
          host: "alerthub-sandbox-api.ifrc.org"
          tls:
            secretName: "alerthub-helm-secret-cert"
        azure:
          aksSecretsProviderAvailable: true
          keyvault:
            name: "alert-hub-playground-key"
            clientId: "f1b1a632-68d6-4e5d-8a1e-d416e98b41a4"
            tenantId: "a2b53be5-734e-4e6c-ab0d-d184f60fd917"
        env:
          APP_FRONTEND_HOST: "https://alerthub-sandbox.ifrc.org"
          APP_DOMAIN: "alerthub-sandbox-api.ifrc.org"
          DJANGO_ALLOWED_HOSTS: "alerthub-sandbox-api.ifrc.org"
          SESSION_COOKIE_DOMAIN: ".ifrc.org"
          CSRF_COOKIE_DOMAIN: ".ifrc.org"
          CORS_ALLOWED_ORIGINS: "https://alerthub-sandbox.ifrc.org"
          # Blob Storage Configs
          USE_AZURE_STORAGE: True
          AZURE_STORAGE_MEDIA_CONTAINER: alert-hub-playground-media-container
          AZURE_STORAGE_STATIC_CONTAINER: alert-hub-playground-static-container
          AZURE_STORAGE_ACCOUNT_NAME: goplaygroundstorage
          AZURE_STORAGE_MANAGED_IDENTITY: True
          AZURE_STORAGE_TOKEN_CREDENTIAL: None
        serviceAccount:
          create: true
          name: "alert-hub-sa"
          annotations:
            azure.workload.identity/client-id: "f1b1a632-68d6-4e5d-8a1e-d416e98b41a4"
          labels:
            azure.workload.identity/use: "true"
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: alert-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true