apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-hub-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/ifrcgo/alert-hub-web-app
    chart: ifrcgo-web-app-nginx-serve
    targetRevision: 0.0.1-develop.d39f061
    helm:
      parameters:
        - name: ingress.host
          value: "alerthub-sandbox.ifrc.org"
        - name: ingress.className
          value: "webapprouting.kubernetes.azure.com"
        - name: env.APP_MAPBOX_ACCESS_TOKEN
          value: "pk.ab.xy"
  destination:
    server: https://kubernetes.default.svc
    namespace: alert-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true