apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-alert-hub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Image list for ArgoCD Image Updater to track
    argocd-image-updater.argoproj.io/image-list: |
      api=ghcr.io/ifrcgo/alert-hub-backend/ifrcgo-alert-hub-helm-alpha:0.0.1-project-phase-2.6c0781f

    # Set the update strategy to pick the latest matching tag
    argocd-image-updater.argoproj.io/api.update-strategy: digest

    # Specifying Helm parameter names
    argocd-image-updater.argoproj.io/api.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/api.helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/IFRCGo/go-risk-module-api
    targetRevision: feature/helm-chart-secrets-config
    path: helm
    helm:
      parameters:
        - name: image.repository
          value: ghcr.io/ifrcgo/alert-hub-backend/ifrcgo-alert-hub-helm-alpha
        - name: image.tag
          value: 0.0.1-project-phase-2.6c0781f
      valueFiles:
        - values-test.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: alert-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true