#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: alert-hub
#  namespace: argocd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
#  annotations:
#    # Image list for ArgoCD Image Updater to track
#    argocd-image-updater.argoproj.io/image-list: |
#      api=docker pull ghcr.io/ifrcgo/alert-hub-backend:develop.448e946
#
#    # Set the update strategy to pick the latest matching tag
#    argocd-image-updater.argoproj.io/api.update-strategy: digest
#
#    # Specifying Helm parameter names
#    argocd-image-updater.argoproj.io/api.helm.image-name: image.repository
#    argocd-image-updater.argoproj.io/api.helm.image-tag: image.tag
#spec:
#  project: default
#  source:
#    repoURL: https://github.com/IFRCGo/alert-hub-backend
#    targetRevision: feature/helm-chart-secrets-config
#    path: helm
#    helm:
#      valueFiles:
#        - values-sandbox.yaml
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: alert-hub
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#    syncOptions:
#      - CreateNamespace=true

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alert-hub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Image list for ArgoCD Image Updater to track
    argocd-image-updater.argoproj.io/image-list: |
      api=ghcr.io/ifrcgo/alert-hub-backend

    # Set the update strategy to pick the latest matching tag
    argocd-image-updater.argoproj.io/api.update-strategy: latest
    argocd-image-updater.argoproj.io/api.allow-tags: regexp:^develop.*$

    argocd-image-updater.argoproj.io/api.helm.image-name: image.name
    argocd-image-updater.argoproj.io/api.helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: ghcr.io/ifrcgo/alert-hub-backend
    chart: ifrcgo-alert-hub-helm
    targetRevision: 0.0.1-develop.d8e2386
    helm:
#      parameters:
#        - name: image.tag
#          value: "develop.d8e2386"
      valueFiles:
        - values-sandbox.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: alert-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true