apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ifrcgo-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ifrcgo
  source:
    repoURL: ghcr.io/ifrcgo/go-api
    chart: ifrcgo-helm
    targetRevision: 0.0.2-develop.c4963628
    helm:
      valueFiles:
        - ./values/go-api-playground-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ifrcgo-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
