apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: risk-module
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Image list for ArgoCD Image Updater to track
    argocd-image-updater.argoproj.io/image-list: |
      api=ghcr.io/ifrcgo/go-risk-module-api:test

    # Set the update strategy to pick the latest matching tag
    argocd-image-updater.argoproj.io/api.update-strategy: digest

    # Specifying Helm parameter names
    argocd-image-updater.argoproj.io/api.helm.image-name: image.name
    argocd-image-updater.argoproj.io/api.helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/IFRCGo/go-risk-module-api
    targetRevision: feature/helm-chart
    path: helm
    helm:
      valueFiles:
        - values-test.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ifrcgo-risk-module
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true