apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-risk-module
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Image list for ArgoCD Image Updater to track
    argocd-image-updater.argoproj.io/image-list: |
      api=ghcr.io/ifrcgo/go-risk-module-api:test
#      api=ghcr.io/ifrcgo/go-risk-module-api:dev-.*

    # Set the update strategy to pick the latest matching tag
    argocd-image-updater.argoproj.io/api.update-strategy: digest

    # Specifying Helm parameter names
    argocd-image-updater.argoproj.io/api.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/api.helm.image-tag: image.tag

    # Optionally, you can add more annotations to control sync behavior
    #argocd.argoproj.io/sync-wave: "0"

spec:
  project: default
  source:
    repoURL: https://github.com/IFRCGo/go-risk-module-api
    targetRevision: feature/helm-chart
    path: helm/go-risk-api
    helm:
      valueFiles:
        - values-test.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true