apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: "0.11.0"
    helm:
      values: |
        config:
          registries:
            - name: ghcr.io
              api_url: https://ghcr.io
              prefix: ghcr.io
              credentials: secret:argocd/ghcr-secret#.dockerconfigjson
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true